# Root directory for storing all downloaded data
root_dir = "." # Mandatory, must be set to the folder that you will store exported data in


[vass]
# Vass username, password and grid password
# Grid password should be given as a list of [x,y] coordinates
username = ""
password = """"""
grid_password = [[1, 1], [6, 1], [1, 3], [6, 3], [1, 6], [6, 6]] # sample grid
# Default vass downloads file structure
dir = "vass exports"
student_details_dir = "personal details summary"
school_program_dir = "school program summary"
predicted_scores_dir = "predicted scores"
school_scores_dir = "school scores"
gat_scores_dir = "gat scores"
external_scores_dir = "external scores"
moderated_coursework_scores_dir = "moderated coursework scores"


[compass]
# Compass username, password and school code
username = ''
password = ''
school_code = ""
# Default compass downloads file structure
dir = "compass exports"
student_details_dir = "student details"
student_details_csv = "student details.csv"
student_household_information_csv = "student household information.csv"
sds_dir = "SDS export"
learning_tasks_dir = "learning tasks"
reports_dir = "reports"
progress_reports_dir = "progress reports"
subjects_dir = "subjects"
class_details_dir = "class details"
enrolment_details_dir = "enrolment details"
reports_csv = "reports.csv"
reports_summary_csv = "reports_summary.csv"
academic_groups_json = "academic groups.json"
progress_report_cycles_json = "progress report cycles.json"
report_cycles_json = "report cycles.json"
subjects_csv = "subjects.csv"
classes_csv = "classes.csv"
attendance_halfday_dir = "attendance halfday"

# Order of all learning task, report and progress report grades, ordered
# lowest to highest
grade_order = [
    "Exempt", "Modified", "Not Demonstrated", "Unsatisfactory", "Rarely",
    "Below Standard", "Satisfactory", "Sometimes", "Competent", "Good", 
    "Very Good", "Usually", "Excellent", "Consistently", "Outstanding" # sample
]

[compass.learning_tasks]
# School-particular learning task metadata
[compass.learning_tasks.result_values]
# Mapping of learning task grades to score values
"Not Demonstrated" = 0.35
"Below Standard" = 0.46
"Satisfactory" = 0.55
"Competent" = 0.64
"Good" = 0.73
"Very Good" = 0.82
"Excellent" = 0.91
"Outstanding" = 1.0

# School-particular reports metadata
[compass.reports.result_values]
# Mapping of reports grades to scores
"Unsatisfactory" = 0.35
"Satisfactory" = 0.55
"Good" = 0.73
"Very Good" = 0.82
"Excellent" = 1.0

[compass.progress_reports]
# School-particular progress reports metadata
# Titles of progress report items
progress_report_items = [ 
    "Completes all set learning", "Contribution in class", "Perseverance",
    "Ready to learn", "Respectfully works/communicates with others",
    "Uses feedback to improve" # sample
]
[compass.progress_reports.result_values]
# Mapping of progress reports grades to scores
"Rarely" = 0.25
"Sometimes" = 0.5
"Usually" = 0.75
"Consistently" = 1.0

# General substitutions to make to Compass exports
# Formatted as compass.replace_values.<field>.<original value> = <replace value>
# Useful for consolidating values in SubjectName, SubjectCode and Result fields 
# that should be treated as equivalent, such as when they have changed over time
[compass.replace_values.SubjectName]
"11 Computing" = "11 Applied Computing" # sample
[compass.replace_values.Result]
"Needs Improvement" = "Below Standard" # sample
[compass.replace_values.SubjectCode]
"GTR" = "GTAR" # sample


[naplan]
# VCAA dataservice username and password
username = ""
password = ""
# Default naplan data file structure
dir = "naplan exports"
outcomes_dir = "outcomes exports"
sssr_dir = "sssr exports"
outcomes_combined_csv = "NAPLAN outcomes combined.csv"
outcomes_most_recent_csv = "NAPLAN outcomes most recent.csv"

[oars]
# ACER OARS username, password and school code
username = ""
password = ""
school_code = ""
# Settings for adding tags to student import files
tag_enrolment_cycles = ["2023 Academic", "2022 Academic"]
tag_enrolment_class_pattern = "(?P<class_code>1?[0789]M[AM]M?[BEFGPQRSTU][12345]|11FM[PQRSTU]1|1?[012789]E[AN]L?[BEFGPQRSTU][12345])"
tag_to_keep_patterns = ['utor']
# Default OARS export file structure
dir = "OARS exports"
pat_scores_csv = "pat scores.csv"
pat_most_recent_csv = "pat most recent.csv"
ewrite_scores_csv = "eWrite scores.csv"
ewrite_criteria_csv = "eWrite criteria.csv"
pat_sittings_dir = "PAT sittings"
ewrite_sittings_dir = "eWrite sittings"
oars_tests_json = "tests.json"
scale_constructs_json = "scale constructs.json"
oars_candidates_json = "candidates.json"

[sportstrak]
dir = "sportstrak

[sportstrak.house_map]
# Map the house colours as given in CASES to the house names as used in Sportstrak
"BLUE" = "F"
"GREEN" = "B"
"RED" = "E"
"GOLD" = "G"

[gcp]
# Google Cloud Platform settings for uploading data to BigQuery
# Note: The GOOGLE_APPLICATION_CREDENTIALS environment variable should be set
# withyour service account key
# GCP project name, GSC bucket name and default BigQuery dataset names
project = "abc-school-data"
gcs_bucket = "abc-school-bucket"
general_dataset = "general_dataset"
vce_dataset = "vce_dataset"
# Default BigQuery table names
[gcp.general_dataset_tables]
student_details_table_id = "student_details"
student_enrolments_table_id = "student_enrolments"
pat_scores_table_id = "pat_scores"
pat_most_recent_table_id = "pat_most_recent"
naplan_outcomes_table_id = "naplan"
naplan_outcomes_most_recent_table_id = "naplan_most_recent"
reports_table_id = "reports"
reports_summary_table_id = "reports_summary"
ewrite_scores_table_id = "ewrite_scores"
ewrite_criteria_table_id = "ewrite_criteria"
gat_table_id = "gat"
[gcp.vce_dataset_tables]
vce_study_scores_table_id = "study_scores"
vce_adjusted_scores_table_id = "adjusted_scores"
